### ISSUE TITLE
Ticking Entity

### ISSUE THREAD

**Issue by NickelHub** [ArcAnc/Thaumic-Gadgets#1]
Seems to be a but with the arrows.

[crash-2018-10-17_18.59.53-server.txt](https://github.com/ArcAnc/Thaumic-Gadgets/files/2488456/crash-2018-10-17_18.59.53-server.txt)

**Comment by Kregoras** [comment]
Happened to me with a trapped dispenser shooting arrows.

**Comment by NickelHub** [comment]
That is actually this, what happened to me.

**Comment by Kregoras** [comment]
So, is this dead or what?

**Comment by NickelHub** [comment]
Be patient, please.

**Comment by ArcAnc** [comment]
Okey. Will fix ot in new version. But it's really strange, i'm remember what this check was present in code.
