### ISSUE TITLE
Crash using Blast Furnace in last version

### ISSUE THREAD

**Issue by Akaruz64** [ArcAnc/Thaumic-Gadgets#2]
I was using it just fine to smelt native clusters, after the update it crashes.

https://pastebin.com/rL6pA1iE

Minecraft 1.12.2
Forge 2772
Thaumic_Gadgets_1.12.2_0.1.5_tb.26

**Comment by ArcAnc** [comment]
Will fix it today. Already undertand what causing this crash

**Comment by Akaruz64** [comment]
I also found a crash in my test world with the disenchanter, it generated 2 crash logs, maybe they can both help, got them trying to remove Looting III from a Diamond sword into a normal book, dunno if that's how it works,

https://pastebin.com/1WE1jpty

https://pastebin.com/fmUKXntq

Second paste is from DummyCore reporting the ASM modification, dunno if its related, its all i understood from reading the log,

Hope it helps and i'm really happy your taking your time to fix this, i really like the mod, keep up the good work.


Regards
