### ISSUE TITLE
Particle Bug still isn't fixed

### ISSUE THREAD

**Issue by duhadventure** [ArcAnc/Thaumic-Gadgets#3]
Thaumcraft: Beta 26
Forge: 2768
TG: 0.1.5.1

Server still crashes with the particle bug.
https://pastebin.com/qEWivHc0

**Comment by ArcAnc** [comment]
How you get this crash? Coz i can't reproduce it on my test server and don't understand what I must to fix

**Comment by ArcAnc** [comment]
Ok, I'm finally reproduce those crash. It's happens when Thaumcraft and Sponge installed at the same time. It's Thaumcraft particle bug, not my mod. So, pls report it to Thaumcraft issue page.
